const STATICS = {
  NAVMENU_TITLE: "E-COMM",
  HOME: "HOME",
  ELECTRONICS: "ELECTRONICS",
  BOOKS: "BOOKS",
  MUSIC: "MUSIC",
  MOVIES: "MOVIES",
  CLOTHING: "CLOTHING",
  GAMES: "GAMES",
  MORE: "MORE",
  FURNITURE: "FURNITURE",
  ELECTRONIC: "ELECTRONICS",
  TRAVEL: "TRAVEL",
  BOTANICAL: "BOTANICAL",
  CATEGORY_NAME: "CATEGORY NAME",
  NAVBAR_SEARCH_PLACEHOLDER: "Search something",
  FEATURED_PRODUCT: "Featured Product",
  EXPLORE_AND_DISCOVER: "Explore and discover a variety of products",
  FOOTWEAR: "Elegant Footwear",
  CAMERA: "Capture Moments",
  LAMP: "Illuminate Your Work",
  AROMA: "Elevating Your Atmosphere",
  EARPHONES: "Seamless Sound",
  INFINITE_CAROUSEL_TYPE: "Infinite",
};

export default STATICS;
